      PROGRAM ASCIISYN
C     PROGRAM ASCIISYN(TAPE1,TAPE2,OUTPUT,TAPE6=OUTPUT)
C     TAPE1=SPECTRUM INPUT
C     TAPE2=SPECTRUM OUTPUT IN ASCII CARD IMAGES
C     TAPE6=OUTPUT
C     FOR FLUX SPECTRA NMU IS 1
C                                                                               
      COMMON /LINDAT/WL,E,EP,LABEL(2),LABELP(2),OTHER1(2),OTHER2(2),
     1        WLVAC,CENTER,CONCEN, NELION,GAMMAR,GAMMAS,GAMMAW,REF,
     2      NBLO,NBUP,ISO1,X1,ISO2,X2,GFLOG,XJ,XJP,CODE,ELO,GF,GS,GR,GW,
     3        DWL,DGFLOG,DGAMMAR,DGAMMAS,DGAMMAW,EXTRA1,EXTRA2,EXTRA3
      REAL*8 LINDAT8(14)
      REAL*4 LINDAT(28)
      EQUIVALENCE (LINDAT8(1),WL),(LINDAT(1),NELION)
      REAL*8 WL,E,EP,WLVAC,CENTER,CONCEN
      REAL*8 LABEL,LABELP,OTHER1,OTHER2
      REAL*4 GFLOG,XJ,XJP,CODE,GAMMAR,GAMMAS,GAMMAW
      REAL*4 REF,X1,X2,ELO,GF,GS,GR,GW
      REAL*4 DWL,DGFLOG,DGAMMAR,DGAMMAS,DGAMMAW,EXTRA1,EXTRA2,EXTRA3
      DIMENSION XMU(20),QMU(40),WLEDGE(200),TITLE(74)
      REAL*8 TEFF,GLOG,TITLE,WBEGIN,RESOLU,XMU,WLEDGE
      REAL*8 QMU
      DIMENSION QOUT(4000)
      OPEN(UNIT=1,FORM='UNFORMATTED',READONLY,STATUS='OLD')
      READ(1)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
      WRITE(6,1)TEFF,GLOG,TITLE
    1 FORMAT(5H TEFF,F7.0,7H   GRAV,F7.3/7H TITLE ,74A1)
      IF(IFSURF.EQ.3)NMU=1
      NMU2=NMU+NMU
C      OPEN(UNIT=2,BLOCKSIZE=4800,RECORDSIZE=80,STATUS='NEW',
C     1RECORDTYPE='FIXED')
      WRITE(2,2)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
    2 FORMAT(F10.1,F10.3/6HTITLE ,74A1/F10.3,F10.1,I10,I5,I5/
     1 10F8.4/10F8.4/I10/(5F16.5))
      DO 6 IWL=1,NWL,100
      N100=MIN0(NWL-IWL+1,100)
      J=0
      DO 4 I100=1,N100 
      READ(1)(QMU(I),I=1,NMU2)
      DO 3 I=1,NMU2
      J=J+1
    3 QOUT(J)=QMU(I) 
    4 CONTINUE
      WRITE(2,5)(QOUT(I),I=1,J)
    5 FORMAT(1P8E10.3)
    6 CONTINUE                                                                  
      READ(1)NLINES
      WRITE(2,7)NLINES
    7 FORMAT(I10)
      DO 9 I=1,NLINES
      READ(1)LINDAT8,LINDAT
      WRITE(2,8)WL,GFLOG,XJ,E,XJP,EP,CODE,LABEL,LABELP,
     1WL,NELION,GR,GS,GW,REF,NBLO,NBUP,ISO1,X1,ISO2,X2,OTHER1,OTHER2,
     2WL,GF,WLVAC,GAMMAR,GAMMAS,GAMMAW,CENTER,CONCEN
C     2WL,ELO,GF,WLVAC,GAMMAR,GAMMAS,GAMMAW,CENTER,CONCEN
C     ELO MUST BE RECONSTRUCTED
    8 FORMAT(F10.4,F7.3,F5.1,F12.3,F5.1,F12.3,F9.2,A8,A2,A8,A2/
     1F10.4,I4,3F6.2,A4,2I2,I3,F7.2,I3,F7.2,A8,A2,A8,A2/
     2F10.4,1PE10.3,0PF10.3,1P5E10.3)
    9 CONTINUE
      CALL EXIT
      END
