      PROGRAM ASK
      DIMENSION XMU(20),QMU(40),WLEDGE(200),TITLE(74)
      REAL*8 TEFF,GLOG,TITLE,WBEGIN,RESOLU,XMU,WLEDGE,RATIO
      REAL*8 H,CONT,WAVE
      REAL*8 WBEGIN1,WBEGIN2,WLAST,WBEG,WMID,WEND,RATIOLG
      READ(1)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
      RATIO=1.+1./RESOLU
      RATIOLG=DLOG(RATIO)
      DO 5 IWL=1,NWL                                                 
      READ(1)H,CONT
      R=H/CONT
      WAVE=WBEGIN*RATIO**(IWL-1)
      WRITE(3,33)WAVE,R
   33 FORMAT(F12.5,F8.5)
    5 CONTINUE
      CALL EXIT
      END
