      SUBROUTINE BEGTIME
C     WRITES OUT ELAPSED SYSTEM ACCOUNTING MESSAGE
      PARAMETER (SS$_ABORT='002C'X)
      IF(.NOT.LIB$INIT_TIMER())CALL LIB$STOP(%VAL(SS$_ABORT))
      RETURN
      ENTRY ENDTIME
      IF(.NOT.LIB$SHOW_TIMER())CALL LIB$STOP(%VAL(SS$_ABORT))
      RETURN
      END
