      PROGRAM PLOTGRIDIM
      READ(5,1000)X0,Y0,XEND,YEND,DX,DY
 1000 FORMAT(8F10.6)
      READ(5,1001)
      READ(5,1001)NXSOLID,NYSOLID,NXDOUBLE,NYDOUBLE
 1001 FORMAT(8I10)
      NX=XEND/DX+.5
      NY=YEND/DY+.5
      CALL MAXLENGTH(500)
      CALL INITPLT(70)
C     REALTECH LASER
      CALL START AT (9./32.,0.)
      CALL START AT (X0,Y0)
      DO 11 I=1,NX-1
      X=I*DX
      CALL JUMP TO (X,0.)
      CALL WEIGHT(1)
      IF(MOD(I,NXDOUBLE).EQ.0)CALL WEIGHT(12)
      IF(MOD(I,NXSOLID).EQ.0)CALL LINE TO (X,YEND)
      IF(MOD(I,NXSOLID).NE.0)CALL DOTLINE(X,0.,X,YEND,'C0C0'X)
C     IF(MOD(I,NXSOLID).NE.0)CALL DOTLINE(X,0.,X,YEND,'E0E0'X)
   11 CONTINUE
      DO 12 I=1,NY-1
      Y=I*DY
      CALL JUMP TO (0.,Y)
      CALL WEIGHT(1)
      IF(MOD(I,NYDOUBLE).EQ.0)CALL WEIGHT(12)
      IF(MOD(I,NYSOLID).EQ.0)CALL LINE TO (XEND,Y)
      IF(MOD(I,NYSOLID).NE.0)CALL DOTLINE(0.,Y,XEND,Y,'C0C0'X)
C     IF(MOD(I,NYSOLID).NE.0)CALL DOTLINE(0.,Y,XEND,Y,'E0E0'X)
   12 CONTINUE
      CALL FIN(70)
      CALL EXIT
      END
