      PROGRAM PUNCHLINE
C     READS THE LINE DATA IN A COMPUTED SPECTRUM FILE AND WRITES
C     CARD IMAGES SUITABLE FOR INPUT TO RLINE.  THESE LINES CAN THEN BE
C     EDITTED TO HAND FIT AN OBSERVED SPECTRUM.

      COMMON /LINDAT/WL,E,EP,LABEL(2),LABELP(2),OTHER1(2),OTHER2(2),
     1        WLVAC,CENTER,CONCEN, NELION,GAMMAR,GAMMAS,GAMMAW,REF,
     2      NBLO,NBUP,ISO1,X1,ISO2,X2,GFLOG,XJ,XJP,CODE,ELO,GF,GS,GR,GW,
     3        DWL,DGFLOG,DGAMMAR,DGAMMAS,DGAMMAW,EXTRA1,EXTRA2,EXTRA3
      REAL*8 LINDAT8(14)
      REAL*4 LINDAT(28)
      EQUIVALENCE (LINDAT8(1),WL),(LINDAT(1),NELION)
      REAL*8 RESOLU,RATIO,RATIOLG,SIGMA2,WLBEG,WLEND
      REAL*8 WL,E,EP,WLVAC,CENTER,CONCEN
      REAL*8 LABEL,LABELP,OTHER1,OTHER2
      REAL*8 TEFF,GLOG,TITLE(74),WBEGIN
C
      REWIND 7
      READ(7)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL
C     SKIP SPECTRUM
      DO 33 IWL=1,NWL
   33 READ(7)
C
      READ(7)NLINES
      DO 70 ILINE=1,NLINES
      READ(7)LINDAT8,LINDAT
      WRITE(6,99)WL,GFLOG,XJ,E,XJP,EP,CODE,LABEL,LABELP,
     1WL,NELION,GR,GS,GW,REF,NBLO,NBUP,ISO1,X1,ISO2,X2,OTHER1,OTHER2
   99 FORMAT(F10.4,F7.3,F5.1,F12.3,F5.1,F12.3,F9.2,A8,A2,A8,A2/
     1F10.4,I4,F6.2,F6.2,F6.2,A4,I2,I2,I3,F7.3,I3,F7.3,A8,A2,A8,A2)
   70 CONTINUE
      CALL EXIT
      END
