      PROGRAM SQUASHSYN
C     REDUCES THE RESOLUTION AND NUMBER OF POINTS BY THE SAME FACTOR
C     WHICH MUST BE AN ODD INTEGER
      REAL*8 LINDAT8(14)
      REAL*4 LINDAT(28)
      DIMENSION XMU(20),QMU(40),WLEDGE(200),TITLE(74)
      REAL*8 TEFF,GLOG,TITLE,WBEGIN,RESOLU,XMU,WLEDGE,RATIO
      REAL*8 QMU,SUMQMU(40)
      REAL*8 WBEGIN1,WBEGIN2,WLAST,WBEG,WMID,WEND,RATIOLG
C
      READ(1)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
      READ(5,1)AVERAGEN
    1 FORMAT(8F10.4)
      RATIO=1.+1./RESOLU
      RATIOLG=DLOG(RATIO)
      NAV=AVERAGEN
      NWL=NWL/NAV
      NMU2=NMU*2
      RESOLU=RESOLU/NAV
      WBEGIN=WBEGIN*RATIO**(NAV/2+1)
      WRITE(2)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
      DO 9 IWL=1,NWL*NAV,NAV                                                 
      DO 3 I=1,NMU2
    3 SUMQMU(I)=0
      DO 5 NU=1,NAV
      READ(1)(QMU(I),I=1,NMU2)
      DO 4 I=1,NMU2
    4 SUMQMU(I)=SUMQMU(I)+QMU(I)     
    5 CONTINUE
      DO 6 I=1,NMU2
    6 SUMQMU(I)=SUMQMU(I)/NAV 
      WRITE(2)(SUMQMU(I),I=1,NMU2)
    9 CONTINUE
C
      NLINES=0
      WRITE(2)NLINES
      CALL EXIT
      END
