$SETSYNTHE
$FOR/LIS MAKESOLARFLUX
$TYPE MAKESOLARFLUX
$LINK MAKESOLARFLUX
$ASSIGN POOLF:SOLARFLUX.ASC FOR011
$ASSIGN POOLF:SOLARFLUX.DAT FOR012
$ASSIGN POOLF:SOLARFLUXINT.DAT FOR013
$ASSIGN POOLF:SOLARFLUXINT10.DAT FOR014
$RUN MAKESOLARFLUX
