$DIR == "DIR/SIZE:ALL/DAT/WIDTH=FILE:35"
$SET DEF KU5E:[ATOMS.0100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0605]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0705]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0706]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0805]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0806]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0807]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0905]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0906]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0907]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.0908]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1005]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1006]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1007]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1008]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1009]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1105]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1106]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1107]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1108]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1109]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1110]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1205]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1206]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1207]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1208]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1209]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1210]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1211]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1305]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1306]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1307]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1308]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1309]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1310]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1311]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1312]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1405]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1406]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1407]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1408]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1409]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1410]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1411]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1412]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1413]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1505]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1506]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1507]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1508]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1509]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1510]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1511]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1512]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1513]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1514]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1605]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1606]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1607]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1608]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1609]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1610]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1611]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1612]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1613]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1614]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1615]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1705]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1706]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1707]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1708]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1709]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1710]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1711]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1712]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1713]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1714]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1715]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1716]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1805]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1806]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1807]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1808]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1809]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1810]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1811]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1812]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1813]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1814]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1815]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1816]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1817]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1905]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1906]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1907]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1908]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1909]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1910]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1911]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1912]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1913]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1914]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1915]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1916]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1917]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.1918]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2005]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2006]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2007]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2008]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2009]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2010]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2011]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2012]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2013]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2014]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2015]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2016]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2017]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2018]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2019]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2105]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2106]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2107]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2108]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2109]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2110]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2111]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2112]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2113]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2114]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2115]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2116]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2117]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2118]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2119]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2120]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2205]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2206]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2207]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2208]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2209]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2210]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2211]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2212]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2213]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2214]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2215]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2216]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2217]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2218]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2219]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2220]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2221]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2305]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2306]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2307]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2308]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2309]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2310]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2311]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2312]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2313]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2314]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2315]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2316]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2317]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2318]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2319]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2320]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2321]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2322]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2405]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2406]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2407]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2408]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2409]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2410]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2411]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2412]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2413]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2414]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2415]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2416]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2417]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2418]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2419]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2420]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2421]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2422]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2423]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2505]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2506]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2507]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2508]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2509]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2510]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2511]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2512]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2513]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2514]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2515]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2516]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2517]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2518]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2519]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2520]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2521]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2522]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2523]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2524]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2605]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2606]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2607]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2608]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2609]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2610]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2611]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2612]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2613]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2614]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2615]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2616]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2617]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2618]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2619]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2620]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2621]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2622]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2623]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2624]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2625]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2705]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2706]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2707]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2708]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2709]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2710]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2711]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2712]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2713]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2714]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2715]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2716]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2717]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2718]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2719]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2720]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2721]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2722]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2723]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2724]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2725]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2726]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2805]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2806]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2807]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2808]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2809]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2810]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2811]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2812]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2813]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2814]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2815]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2816]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2817]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2818]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2819]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2820]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2821]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2822]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2823]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2824]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2825]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2826]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2827]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2905]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2906]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2907]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2908]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2909]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2910]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2911]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2912]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2913]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2914]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2915]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2916]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2917]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2918]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2919]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2920]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2921]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2922]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2923]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2924]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2925]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2926]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2927]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.2928]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3005]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3006]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3007]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3008]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3009]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3010]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3011]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3012]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3013]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3014]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3015]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3016]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3017]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3018]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3019]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3020]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3021]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3022]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3023]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3024]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3025]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3026]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3027]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3028]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3029]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.3904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.4904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.5904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.6904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.7904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8000]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.8904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9001]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9002]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9003]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9004]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9100]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9101]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9102]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9103]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9104]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9200]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9201]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9202]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9203]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9204]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9300]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9301]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9302]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9303]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9304]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9400]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9401]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9402]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9403]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9404]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9500]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9501]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9502]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9503]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9504]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9600]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9601]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9602]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9603]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9604]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9700]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9701]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9702]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9703]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9704]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9800]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9801]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9802]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9803]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9804]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9900]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9901]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9902]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9903]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.9904]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.AEL]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.HF]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.PF]
$DIR/OUT=CREATIONDATES.DAT
$SET DEF KU5E:[ATOMS.PROGRAMS]
$DIR/OUT=CREATIONDATES.DAT
