$SETSYNTHE
$FOR/LIS/G MAKESOLARFLUX
$TYPE MAKESOLARFLUX
$LINK MAKESOLARFLUX
$ASSIGN KUR5:[KURUCZ]SOLARFLUX.ASC FOR011
$ASSIGN KUR5:[KURUCZ]SOLARFLUX.DAT FOR012
$ASSIGN KUR5:[KURUCZ]SOLARFLUXINT.DAT FOR013
$ASSIGN KUR5:[KURUCZ]SOLARFLUXINT10.DAT FOR014
$RUN MAKESOLARFLUX
