      PROGRAM RTIOBINASC
C     READS PACKED BINARY VERSION OF SCHWENKE'S TIO LINELIST
C     WRITES PACKED ASCII
      INTEGER*2 IELION,IELO,IGFLOG,IGR,IGS,IGW
      INTEGER*4 IWL
      OPEN(UNIT=11,STATUS='OLD',FORM='UNFORMATTED',
     1RECORDTYPE='FIXED',BLOCKSIZE=8000,RECORDSIZE=4)
      OPEN(UNIT=12,STATUS='NEW',CARRIAGECONTROL='LIST')
      DO 20 ILINE=1,37744499
      READ(11)IWL,IELION,IELO,IGFLOG,IGR,IGS,IGW
      WRITE(12,12)IWL,IELION,IELO,IGFLOG,IGR,IGS,IGW
   12 FORMAT(I8,6I5)
   20 CONTINUE
      CALL EXIT
      END
