      PROGRAM KPNOBIN
      DIMENSION ISPECT(500)
      INTEGER*2 LAMBDA,NORD,NSET,NREC,ISPECT
      DO 5 I=1,13997
      READ(1,1)LAMBDA,NORD,NSET,NREC,ISPECT
    1 FORMAT(16I5)
      PRINT 2,I,LAMBDA,NORD,NSET,NREC
    2 FORMAT(5I10)
      WRITE(2)LAMBDA,NORD,NSET,NREC,ISPECT
    5 CONTINUE
      CALL EXIT
      END
