$SETSYNTHE
$FOR/G/LIS ETIOSCHWENKEBIN.FOR
$TYPE ETIOSCHWENKEBIN.LIS
$LINK ETIOSCHWENKEBIN.OBJ
$ASSIGN K:ETIOSCHWENKE46.ASC FOR011
$ASSIGN K:ETIOSCHWENKE47.ASC FOR012
$ASSIGN K:ETIOSCHWENKE48.ASC FOR013
$ASSIGN K:ETIOSCHWENKE49.ASC FOR014
$ASSIGN K:ETIOSCHWENKE50.ASC FOR015
$ASSIGN K:ETIOSCHWENKE.BIN FOR007
$RUN ETIOSCHWENKEBIN
