$SETTIO
$FOR/LIS RTIOBINCARD
$TYPE RTIOBINCARD
$LINK RTIOBINCARD
$ASSING TIO:ETIOSCHWENKE.BIN FOR048
$ASSIGN KU2C:[KURUCZ]TIOSCHWENKE.BIN FOR011
$ASSIGN KU2C:[KURUCZ]TIOSCHWENKE.IDASC FOR012
$RUN RTIOBINCARD
