      PROGRAM RESAMPLE
C     REDUCES THE SAMPLING FOR A BROADENED SPECTRUM BY AN ODD INTEGER
      REAL*8 LINDAT8(14)
      REAL*4 LINDAT(28)
      DIMENSION XMU(20),QMU(40),WLEDGE(377),TITLE(74)
      REAL*8 TEFF,GLOG,TITLE,WBEGIN,RESOLU,XMU,WLEDGE,RATIO
      REAL*8 QMU,SUMQMU(40)
      REAL*8 WBEGIN1,WBEGIN2,WLAST,WBEG,WMID,WEND,RATIOLG
C
      READ(1,err=11)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,
     1NEDGE,WLEDGE
      go to 12
   11 REWIND 1
      READ(1)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE
   12 continue
      READ(5,1)RESAMP
    1 FORMAT(8F10.4)
      RATIO=1.D0+1.D0/RESOLU
      RATIOLG=DLOG(RATIO)
      NRESAMP=RESAMP
      IFSURF=IFSURF+10*NRESAMP
      NWL=NWL/NRESAMP
      NMU2=NMU*2
      WBEGIN=WBEGIN*RATIO**(NRESAMP/2+1-1)
      WRITE(2)TEFF,GLOG,TITLE,WBEGIN,RESOLU,NWL,IFSURF,NMU,XMU,NEDGE,
     1WLEDGE
      DO 9 IWL=1,NWL                                                
      DO 7 ISKIP=1,NRESAMP/2
    7 READ(1)
      READ(1)(QMU(I),I=1,NMU2)
      WRITE(2)(QMU(I),I=1,NMU2)
      DO 8 ISKIP=1,NRESAMP/2
    8 READ(1)
    9 CONTINUE
C
      NLINES=0
      WRITE(2)NLINES
      CALL EXIT
      END
