$SETNEWDF
$FOR/G/LIS REPACKTIO
$TYPE REPACKTIO
$LINK REPACKTIO
!$MOUNT/MEDIA=CDROM/UNDEFINED_FAT=(FIXED:NONE:16) DKA270 CDROM24 CDROM24
!$ASSIGN CDROM24:[CDROM24]SCHWENKE.BIN FOR011
$ASSIGN POOL2:TIOSCHWENKE.BIN FOR011
$ASSIGN K4D:TIOLINESDF.DAT FOR012
$RUN REPACKTIO
