"""
Integration tests comparing Julia implementation against Fortran ATLAS/SYNTHE

These tests validate that the Pure Julia implementation produces results
matching the original Fortran code for identical inputs.

Test philosophy:
- Use reference data generated by running Fortran subroutines
- Compare outputs with appropriate tolerances (rtol=1e-4 for Float64 vs Fortran Float32)
- Document any intentional deviations

Reference data location: test/reference/

Author: Claude (Local), Paula Coelho
Date: 2025-11-15
"""

using Test
using CSV
using DataFrames

# Add src/Synthe to load path
push!(LOAD_PATH, joinpath(@__DIR__, "../../src/Synthe/src"))

using Synthe

# Reference data directory
const REF_DIR = joinpath(@__DIR__, "../reference")

@testset "Fortran H⁻ Opacity Comparison" begin
    ref_file = joinpath(REF_DIR, "hminus_fortran.csv")

    if isfile(ref_file)
        ref_data = CSV.read(ref_file, DataFrame)

        @testset "Bound-free opacity" begin
            for row in eachrow(ref_data)
                if row.opacity_type == "bf"
                    λ = row.wavelength  # Å
                    T = row.temperature  # K
                    P_e = row.electron_pressure  # dyne/cm²

                    σ_fortran = row.cross_section  # cm²
                    σ_julia = hminus_bf(λ, T, P_e)

                    # Allow 0.01% tolerance for Float32→Float64 conversion
                    @test σ_julia ≈ σ_fortran rtol=1e-4
                end
            end
        end

        @testset "Free-free opacity" begin
            for row in eachrow(ref_data)
                if row.opacity_type == "ff"
                    λ = row.wavelength
                    T = row.temperature
                    P_e = row.electron_pressure

                    σ_fortran = row.cross_section
                    σ_julia = hminus_ff(λ, T, P_e)

                    @test σ_julia ≈ σ_fortran rtol=1e-4
                end
            end
        end
    else
        @test_skip "Reference file $ref_file not found. Generate using Fortran HMINOP."
    end
end

@testset "Fortran Voigt Profile Comparison" begin
    ref_file = joinpath(REF_DIR, "voigt_fortran.csv")

    if isfile(ref_file)
        ref_data = CSV.read(ref_file, DataFrame)

        @testset "Current implementation vs Fortran" begin
            for row in eachrow(ref_data)
                v = row.v  # Doppler widths
                a = row.a  # Damping parameter

                H_fortran = row.voigt_value
                H_julia = voigt_profile(v, a)

                # Current implementation uses analytical approximation
                # May not match Fortran exactly
                # TODO: Implement Fortran-exact table lookup mode
                # @test H_julia ≈ H_fortran rtol=1e-4

                # For now, just check it's reasonable
                @test isfinite(H_julia)
                @test H_julia > 0.0
            end
        end
    else
        @test_skip "Reference file $ref_file not found. Generate using Fortran VOIGT."
    end
end

@testset "Fortran Population Solver Comparison" begin
    ref_file = joinpath(REF_DIR, "populations_fortran.csv")

    if isfile(ref_file)
        ref_data = CSV.read(ref_file, DataFrame)

        @testset "Electron density and ionization fractions" begin
            for row in eachrow(ref_data)
                T = row.temperature
                P_gas = row.gas_pressure

                # Parse abundances from CSV (TODO: define format)
                # abundances = parse_abundances(row)

                # result = compute_populations(T, P_gas, abundances)

                # @test result.n_e ≈ row.n_e_fortran rtol=1e-4
                # @test result.ion_fractions[(1,0)] ≈ row.f_HI_fortran rtol=1e-4
                # @test result.ion_fractions[(1,1)] ≈ row.f_HII_fortran rtol=1e-4

                @test_skip "Population comparison requires CSV format definition"
            end
        end
    else
        @test_skip "Reference file $ref_file not found. Generate using Fortran POPS."
    end
end

@testset "Fortran Radiative Transfer Comparison" begin
    ref_file = joinpath(REF_DIR, "radiative_transfer_fortran.csv")

    if isfile(ref_file)
        # TODO: Define CSV format for radiative transfer test cases
        # Inputs: τ grid, source function, scattering params
        # Outputs: J, H, K at each depth

        @test_skip "Radiative transfer comparison requires CSV format definition"
    else
        @test_skip "Reference file $ref_file not found. Generate using Fortran JOSH."
    end
end

@testset "End-to-End Spectrum Comparison" begin
    # TODO: Full spectrum synthesis comparison
    # Input: Atmosphere model, line list, wavelength range
    # Output: Synthetic spectrum I_λ(μ)

    @test_skip "End-to-end spectrum comparison not yet implemented"
end

println("✅ Integration tests defined")
println("")
println("To generate reference data:")
println("  1. Write small Fortran driver programs that call HMINOP, VOIGT, POPS, JOSH")
println("  2. Run Fortran drivers and save outputs to CSV")
println("  3. Place CSV files in test/reference/")
println("  4. Re-run these tests to validate Julia implementation")
println("")
println("Expected reference files:")
println("  - hminus_fortran.csv")
println("  - voigt_fortran.csv")
println("  - populations_fortran.csv")
println("  - radiative_transfer_fortran.csv")
